name: Deploy to Amazon Lambda

on:
  push:
    branches:
      - "master"

env:
  AWS_REGION: AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
  S3_BUCKET: S3_BUCKET


permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: aws-actions/setup-sam@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: $AWS_REGION
    # sam build 
    - run: sam build --use-container -t TestFunc/template.yml

# Run Unit tests- Specify unit tests here 

# sam deploy
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name test-func --s3-bucket $S3_BUCKET --capabilities CAPABILITY_IAM --region $AWS_REGION 
